/* global use, db */
// MongoDB Playground
// To disable this template go to Settings | MongoDB | Use Default Template For Playground.
// Make sure you are connected to enable completions and to be able to run a playground.
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.
// The result of the last command run in a playground is shown on the results panel.
// By default the first 20 documents will be returned with a cursor.
// Use 'console.log()' to print to the debug output.
// For more documentation on playgrounds please refer to
// https://www.mongodb.com/docs/mongodb-vscode/playgrounds/

// Select the database to use.
use('ayurdaily');

// Insert a few documents into the sales collection.
db.connections.insertMany([
    {name: "Almond Shea Moisturizer", topic: "Skin Care", prodOneLine: "Moist your skin with the Almond Shea Moisturizer!", hostname: "Bella", location: "Woodward 1", cost: "$20", Significance: "Best for dry skins, dry weather.", details: "The optimal skin types for this moisturizer are dry skin and skin that develops rashes in cold temperatures. Almond Shea moisturizer gives the skin a healthy glow that lasts for up to 24 hours Shea extract, milk, almonds, and rose water are all included in the moisturizer", image: "https://umbelorganics.com/wp-content/uploads/2020/12/lotion_jar.jpg"},
    {name: "AloeNeem Ayur Soap", topic: "Skin Care", prodOneLine: "Vanish germs, welcome natural skin!", hostname: "Max", location: "Woodward 2", cost: "$15", Significance: "Use regularly to get bacterial free body", details: "It is a perfect solution if you want germ free plus hydrated body. The soap is made up of Aloe Vera which helps in cleansing the body and Neem fights against germs.", image: "https://thenerdyfarmwife.com/wp-content/uploads/2018/04/aloe-vera-facial-soap-1200FB.jpg"},
    {name: "Gram Face Pack", topic: "Skin Care", prodOneLine: "Do not just eat Gram seeds but use them for Glow!", hostname: "Bob", location: "Woodward 3", cost: "$23", Significance: "Best for dry skins and instant glow", details: "Gram Face Pack consists of proceeded gram seeds, rose water, oil,coffee extract. Apply the pack on face and keep it for 10 mins. Then gently wipe your face with damp cloth. Use twice a week.", image: "https://www.thepinkvelvetblog.com/wp-content/uploads/2019/01/Besan-Gram-Flour-Haldi-Turmeric-and-Dahi-Curd-Face-Pack-for-a-Problem-Free-Skin.jpg"},
    {name: "Ayur Serum", topic: "Skin Care", prodOneLine: "Removes black heads", hostname: "Alice", location: "Woodward 4", cost: "$55", Significance: "Get rid of acne, black heads and opens pores", details: "Apply at night so that skin heals quickly. Apply 2-3 drops only.", image: "https://img.freepik.com/premium-photo/brown-glass-bottles-with-dropper-dispenser-sand-background-bottles-cosmetic-oil-serum-without-logo-label-blank-mock-up-cosmetics-product_286227-3001.jpg?w=740"},
    {name: "Onion Extract Shampoo", topic: "Hair & Care", prodOneLine: "Nourishes scalp with Onion rich proteins", hostname: "Mike", location: "Woodward 5", cost: "$25", Significance: "Avoids hairfall and improves hair growth", details: "Organic forest hundres percent vegan and black seed oil. Shampoo for women and men.", image: "https://i.etsystatic.com/12883017/r/il/d49e58/3096344633/il_1080xN.3096344633_n8kh.jpg"},
    {name: "Almond oil", topic: "Hair & Care", prodOneLine: "Use almond oil when creating your personal care formulation to keep your skin healthy smooth and soft", hostname: "Sandra", location: "Woodward 6", cost: "$15", Significance: "Improves hair growth", details: "This transparent oil is ideal for soaps, candles, vapourisers, lotions and diffusers. Craft with oils and natural creativity", image: "https://www.rusticescentuals.com/Images/Products/almond-oil.jpg"},
    {name: "Jasmine Hair Gel", topic: "Hair & Care", prodOneLine: "High Hold and Shine", hostname: "Andrew", location: "Woodward 7", cost: "$85", Significance: "Provides moisturising and conditioning benefits", details: "Moisture rich gel that provides defined look while taming hair leaving a high shine and finish.", image: "https://cdn.shopify.com/s/files/1/2395/7673/files/shampoo-conditioner_480x480.jpg?v=1655902483"},
    {name: "Mix fruit hair spray", topic: "Hair & Care", prodOneLine: "Super hold finishing and styling hair spray", hostname: "Whitney", location: "Woodward 8", cost: "$35", Significance: "Provides moisturising and conditioning benefits", details: "Leaves hair looking natural and shining while imparting strength and volume.", image: "https://thumbs.dreamstime.com/b/aerosol-spray-can-bottle-white-background-flowers-gypsophila-fresh-citrus-fruits-hair-care-concept-metal-cosmetic-175937696.jpg"},
    {name: "Aloe Soft Razor", topic: "Hygiene and More", prodOneLine: "Blade and a lubra strip for glide to deliver a smooth shave", hostname: "Sandrapp", location: "Woodward 9", cost: "$65", Significance: "Safe shave with cooling effect.", details: "Made with protective elastomer comfort cushions around the blade.", image: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81r+gbipYML.jpg"},
    {name: "pH Balanaced Wash", topic: "Hygiene and More", prodOneLine: "Unique pH balance formula of lactic acid", hostname: "Sandy", location: "Woodward 10", cost: "$61", Significance: "Vaginal hygiene with pH 3.5 and above", details: "The best defense against any vaginal discomfort.", image: "https://assets.fishersci.com/TFS-Assets/CCG/product-images/CHWB1004_2.jpg-650.jpg"},
    {name: "After Shave Gel", topic: "Hygiene and More", prodOneLine: "Cooling and refereshing effect and no burns", hostname: "Sandrapp", location: "Woodward 11", cost: "$60", Significance: "Lightly fragnanced for sensitive skin", details: "Perfectly crisp and clean way to refuel your skin after a great shave", image: "https://media.istockphoto.com/id/1224786638/photo/men-cosmetic-product-aftershave-and-white-towel-on-blue-background-with-copy-space.jpg?s=612x612&w=0&k=20&c=9o1dH4b2udH_63ZrGWCcZ4WhUPdhS-HAbDgnXtMlyts="},
    ]);

